### ISSUE TITLE
GET |  /users

### ISSUE THREAD

**Issue by ameera-abed** [GSG-G10/Housy#17]
**Description**
 the admin  can see all the users 

**Files**

- Database -> Queries -> getUsersQuery.js
- Database -> Queries -> index.js
- Controllers -> getUsers.js
- Controllers -> index.js
- Routes -> index.js -> router.get();

**Tasks**

- [x]  Create DB query to get the users from the database
- [x]  Import the query in controllers from DB>QUERIES>index.js and return the data
- [x]  Create GET Route in Routes>index.js
